# Generated by Django 5.2.4 on 2025-08-04 01:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Head', 'Head'), ('Branch', 'Branch')], max_length=10)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('web_address', models.URLField(blank=True, null=True)),
                ('max_capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sender', models.CharField(max_length=255)),
                ('receiver', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body_snippet', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('social_security_number', models.CharField(max_length=20, unique=True)),
                ('medicare_card_number', models.CharField(max_length=20, unique=True)),
                ('telephone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('Administrator', 'Administrator'), ('General Manager', 'General Manager'), ('Deputy Manager', 'Deputy Manager'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary'), ('Captain', 'Captain'), ('Coach', 'Coach'), ('Assistant Coach', 'Assistant Coach'), ('Other', 'Other')], max_length=50)),
                ('mandate', models.CharField(choices=[('Volunteer', 'Volunteer'), ('Salaried', 'Salaried')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('social_security_number', models.CharField(max_length=20, unique=True)),
                ('medicare_card_number', models.CharField(max_length=20, unique=True)),
                ('telephone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('social_security_number', models.CharField(max_length=20, unique=True)),
                ('medicare_card_number', models.CharField(max_length=20, unique=True)),
                ('telephone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('membership_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('hobbies', models.ManyToManyField(blank=True, to='club.hobby')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MinorMemberAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Grandfather', 'Grandfather'), ('Grandmother', 'Grandmother'), ('Tutor', 'Tutor'), ('Partner', 'Partner'), ('Friend', 'Friend'), ('Other', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.familymember')),
                ('minor_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.clubmember')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method_of_payment', models.CharField(choices=[('Cash', 'Cash'), ('Debit', 'Debit Card'), ('Credit', 'Credit Card')], max_length=10)),
                ('for_year', models.PositiveIntegerField()),
                ('club_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.clubmember')),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.location')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryFamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('telephone_number', models.CharField(max_length=20)),
                ('relationship', models.CharField(max_length=50)),
                ('primary_family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_contacts', to='club.familymember')),
            ],
        ),
        migrations.CreateModel(
            name='TeamFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('session_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('session_address', models.CharField(max_length=255)),
                ('is_game', models.BooleanField(default=False)),
                ('score_team1', models.PositiveIntegerField(blank=True, null=True)),
                ('score_team2', models.PositiveIntegerField(blank=True, null=True)),
                ('head_coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coached_teams', to='club.personnel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.location')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Setter', 'Setter'), ('Outside Hitter', 'Outside Hitter'), ('Opposite Hitter', 'Opposite Hitter'), ('Middle Blocker', 'Middle Blocker'), ('Defensive Specialist', 'Defensive Specialist'), ('Libero', 'Libero')], max_length=20)),
                ('club_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.clubmember')),
                ('team_formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='club.teamformation')),
            ],
            options={
                'unique_together': {('club_member', 'team_formation')},
            },
        ),
    ]
