# Generated by Django 5.2.4 on 2025-08-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
