# Generated by Django 5.2.5 on 2025-08-07 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clubmember',
            table=None,
        ),
        migrations.AlterModelTable(
            name='emaillog',
            table=None,
        ),
        migrations.AlterModelTable(
            name='familymember',
            table=None,
        ),
        migrations.AlterModelTable(
            name='familyrelationship',
            table=None,
        ),
        migrations.AlterModelTable(
            name='hobbies',
            table=None,
        ),
        migrations.AlterModelTable(
            name='memberhobbies',
            table=None,
        ),
        migrations.AlterModelTable(
            name='payments',
            table=None,
        ),
        migrations.AlterModelTable(
            name='personnel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='personnelassignment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='playerassignment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='secondaryfamilymember',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sessions',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sessionteams',
            table=None,
        ),
    ]
