# Generated by Django 5.2.4 on 2025-08-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_clubmember_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
